name: phlegeton_character_finance_manager
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  provider: ^6.1.5
  gap: ^3.0.1
  json_serializable: ^6.8.0
  json_annotation: 4.9.0

  build_runner: ^2.4.11
  path_provider: ^2.1.5
  uuid: ^4.5.1
  flutter_svg: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - "assets/backgrounds/theme_l/"
    - "assets/backgrounds/theme_g/"
    - "assets/backgrounds/theme_b/"
    - "assets/backgrounds/theme_t/"
    - "assets/theme_icons/"
